function x10_13Box1 = BehavioralDataImportBox1(filename, dataLines)
%IMPORTFILE Import data from a text file
%  X10_13BOX1 = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a string array.
%
%  X10_13BOX1 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  x10_13Box1 = importfile("C:\Users\vasus\OneDrive\Documents\GitHub\2020_Internship_New\Behavioral Analysis Data\10.13", [5, 271]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 22-Oct-2020 16:19:03

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [5, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ":";

% Specify column names and types
opts.VariableNames = ["File", "C", "Var3", "Var4"];
opts.SelectedVariableNames = ["File", "C"];
opts.VariableTypes = ["string", "string", "char", "char"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["File", "C", "Var3", "Var4"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["File", "C", "Var3", "Var4"], "EmptyFieldRule", "auto");

% Import the data
x10_13Box1 = readmatrix(filename, opts);

end