function ImportDataFiles = ImportDataFiles(filename, dataLines)
%IMPORTFILE Import data from a text file
%  UNTITLED = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a cell array.
%
%  UNTITLED = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  Untitled = importfile("C:\Users\vasus\OneDrive\Documents\GitHub\2020_Internship_New\BehaviorData\1012.txt", [5, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 23-Oct-2020 10:15:12

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [5, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ":";

% Specify column names and types
opts.VariableNames = ["File", "C", "MEDPCIVDATA20201012_14h04mSubject0", "VarName4"];
opts.VariableTypes = ["char", "char", "char", "char"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["File", "C", "MEDPCIVDATA20201012_14h04mSubject0", "VarName4"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["File", "C", "MEDPCIVDATA20201012_14h04mSubject0", "VarName4"], "EmptyFieldRule", "auto");

% Import the data
ImportDataFiles = readtable(filename, opts);

%% Convert to output type
ImportDataFiles = table2cell(ImportDataFiles);
numIdx = cellfun(@(x) ~isnan(str2double(x)), ImportDataFiles);
ImportDataFiles(numIdx) = cellfun(@(x) {str2double(x)}, ImportDataFiles(numIdx));
end